# Generated by Django 3.2.3 on 2021-06-10 11:07

from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('mark1', '0001_initial'),
    ]
    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('gender', models.BooleanField(default=False)),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
